// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Confirm is the predicate function for confirm builders.
type Confirm func(*sql.Selector)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)
