// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"treasure/ent/ent/confirm"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Confirm is the model entity for the Confirm schema.
type Confirm struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// request id
	RequestID int64 `json:"request_id,omitempty"`
	// manager id
	ManagerID int `json:"manager_id,omitempty"`
	// approve or reject
	Approved     bool `json:"approved,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Confirm) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case confirm.FieldApproved:
			values[i] = new(sql.NullBool)
		case confirm.FieldID, confirm.FieldRequestID, confirm.FieldManagerID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Confirm fields.
func (c *Confirm) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case confirm.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int64(value.Int64)
		case confirm.FieldRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				c.RequestID = value.Int64
			}
		case confirm.FieldManagerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field manager_id", values[i])
			} else if value.Valid {
				c.ManagerID = int(value.Int64)
			}
		case confirm.FieldApproved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field approved", values[i])
			} else if value.Valid {
				c.Approved = value.Bool
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Confirm.
// This includes values selected through modifiers, order, etc.
func (c *Confirm) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// Update returns a builder for updating this Confirm.
// Note that you need to call Confirm.Unwrap() before calling this method if this Confirm
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Confirm) Update() *ConfirmUpdateOne {
	return NewConfirmClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Confirm entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Confirm) Unwrap() *Confirm {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Confirm is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Confirm) String() string {
	var builder strings.Builder
	builder.WriteString("Confirm(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", c.RequestID))
	builder.WriteString(", ")
	builder.WriteString("manager_id=")
	builder.WriteString(fmt.Sprintf("%v", c.ManagerID))
	builder.WriteString(", ")
	builder.WriteString("approved=")
	builder.WriteString(fmt.Sprintf("%v", c.Approved))
	builder.WriteByte(')')
	return builder.String()
}

// Confirms is a parsable slice of Confirm.
type Confirms []*Confirm
