// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"treasure/ent/ent/confirm"
	"treasure/ent/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfirmDelete is the builder for deleting a Confirm entity.
type ConfirmDelete struct {
	config
	hooks    []Hook
	mutation *ConfirmMutation
}

// Where appends a list predicates to the ConfirmDelete builder.
func (cd *ConfirmDelete) Where(ps ...predicate.Confirm) *ConfirmDelete {
	cd.mutation.Where(ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *ConfirmDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cd.sqlExec, cd.mutation, cd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *ConfirmDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *ConfirmDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(confirm.Table, sqlgraph.NewFieldSpec(confirm.FieldID, field.TypeInt64))
	if ps := cd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cd.mutation.done = true
	return affected, err
}

// ConfirmDeleteOne is the builder for deleting a single Confirm entity.
type ConfirmDeleteOne struct {
	cd *ConfirmDelete
}

// Where appends a list predicates to the ConfirmDelete builder.
func (cdo *ConfirmDeleteOne) Where(ps ...predicate.Confirm) *ConfirmDeleteOne {
	cdo.cd.mutation.Where(ps...)
	return cdo
}

// Exec executes the deletion query.
func (cdo *ConfirmDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{confirm.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *ConfirmDeleteOne) ExecX(ctx context.Context) {
	if err := cdo.Exec(ctx); err != nil {
		panic(err)
	}
}
